### PR TITLE
Refactor/remove schematron files

### PR DESCRIPTION
**Pull request by macintoshpie**
## context
We're moving schematron files into the [use-cases repo](https://github.com/BuildingSync/use-cases).

## changes
- Delete old documentation and schematron files.
- refactor generate_sch to default the assertion role to `ERROR`
- refactor cli to support schemaVersion attribute when generating
- remove cli commands specific to repo (e.g. generate_all)

### CODE REVIEW

**Review by nllong — APPROVED** [review]
Looks sweet! Thanks for cleaning this all up 🧹. I'm eager to have the new use case repo up and running!

**Comment by macintoshpie** [comment]
@nllong can you update the branch protection settings by removing these two status checks? These were necessary when the schematron was around but not anymore.
Screen Shot 2021-05-19 at 8 59 29 AM

**Comment by macintoshpie** [comment]
Also I think we should make a new release after this, I would like to use the new features for generating sch in the use-cases repo

**Comment by nllong** [comment]
> @nllong can you update the branch protection settings by removing these two status checks? These were necessary when the schematron was around but not anymore.
> Screen Shot 2021-05-19 at 8 59 29 AM

done.

**Comment by nllong** [comment]
> Also I think we should make a new release after this, I would like to use the new features for generating sch in the use-cases repo

🚀🤘

**Pull request merged**
