### PR TITLE
Two new examples added

### PR DESCRIPTION
**Pull request by JieXiong9119**
Two examples that pass multiple use cases:
1. Preliminary analysis + L100 OpenSutdio pre-simulation
2. L100 audit + BSyncr

### CODE REVIEW

**Review by corymosiman12 — CHANGES_REQUESTED** [review]
Hey Jie - looks good, but can you create a test that runs the testsuite validator for the two use cases and only passes when both use cases are valid?

**Comment by corymosiman12** [comment]
@JieXiong9119 looking good! can you add just one more test for the plan `bsyncr.xml` file, just like you've done for the other ones? Once that's done, I think we can merge and close!

**Comment by JieXiong9119** [comment]
> @JieXiong9119 looking good! can you add just one more test for the plain `bsyncr.xml` file, just like you've done for the other ones? Once that's done, I think we can merge and close!

Finally done!

**Review by corymosiman12 — APPROVED** [review]

**Comment by corymosiman12** [comment]
Schnoice!

**Pull request merged**
