### PR TITLE
Add new examples to version 2.3.0

### PR DESCRIPTION
**Pull request by JieXiong9119**
1. Add bsyncr use case (schematron, example, test function)
2. Add examples and test functions for multiple use cases
2.1. L000 audit + L100 OS pre-simulation
2.2. L100 audit + bsyncr

### CODE REVIEW

**Review by corymosiman12 — COMMENTED** [review]
hey @JieXiong9119 - for both the 2.2.0 and 2.3.0 versions, can you add a bsyncr.csv file (similar to the others, see [here for example](https://github.com/BuildingSync/TestSuite/blob/develop/schematron/v2.2.0/v2-2-0_BETTER_input.csv) and then use that to generate the schematron file? That's how we've been managing these, as it is a bear to deal with schematron files on their own :) Likely there should be no change to the bsyncr.sch file (maybe just ordering). Let me know if any of that is unclear, and kudos for writing schematron by hand.

**Comment by corymosiman12** [comment]
@JieXiong9119 will you just add newlines at the end of the csv's (not sure why this isn't getting flagged by pre-commit... @macintoshpie thoughts?): 
image

**Comment by JieXiong9119** [comment]
> @JieXiong9119 will you just add newlines at the end of the csv's (not sure why this isn't getting flagged by pre-commit... @macintoshpie thoughts?):
> image

Manually done. I'm not sure why this is not fixed by the pre-commit.

**Review by corymosiman12 — APPROVED** [review]
👍  schnoice!

**Comment by JieXiong9119** [comment]
@corymosiman12 I think it's ready to merge. I don't have a write access again (weird) so could you merge it?

**Pull request merged**
