### PR TITLE
Feature better analysis

### PR DESCRIPTION
**Pull request by aviveiros11**
Added a new example for running a BETTER analysis with 12 months elec and nat gas meter data.

### CODE REVIEW

**Comment by corymosiman12** [comment]
I would consider calling this '...BETTER Input...', as in the future you might have a schematron on the output side. That was the intention behind the '...Pre-Simulation...', i.e. validate the contents of the file _before_ a simulation is run.

**Review by corymosiman12 — CHANGES_REQUESTED** [review]
Minor change requested, else looks good.

**Review by JieXiong9119 — APPROVED** [review]
Looks good!

**Review by corymosiman12 — APPROVED** [review]
🌭

**Pull request merged**
